### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by OscarFMdev** [OscarFMdev/leaderboardProject#6]
# Morning session code review 💯 

Please, **comment below on the issues of this morning's session!** 🙏 

### Thank you for reviewing my code! 🙌

**Comment by rebaz36** [comment]
# Great work @OscarFMdev 
everything is implemented with consideration to the rules and requirements!

## Good Job Keep up the good work ✅

**Comment by sntgopl** [comment]
### Code looks great @OscarFMdev 

Everything looks good. Just one little thing in the readme file, in the "install" title, it says "Yo" instead of "You.

Also, a suggestion that works fine for me could work for you too also. I tend to use a module to export all the HTML selectors to leave the index.js as clean and empty as possible. You can either take it or leave it.

Anyway, your code looks just great. Good Job!

**Comment by OscarFMdev** [comment]
**- Thank you @rebaz36 !** 
**- And thanks @sntgopl I should do that to keep my code cleaner.** 
### Thank you team! ❤️
